const GLOBAL = {
  COMMON: {
    LITEFLIX: "LITEFLIX",
    LITE: "LITE",
    FLIX: "FLIX",
    ADD_MOVIE: "AGREGAR PELÍCULA",
    IMAGES_URL: "https://image.tmdb.org/t/p/original",
    LOGOUT: "CERRAR SESIÓN",
  },
  HOME: {
    ORIGINAL: "ORIGINAL DE ",
    PLAY: "REPRODUCIR",
    MY_LIST: "MI LISTA",
    WATCH: "VER:",
  },
  MENU: {
    HOME: "INICIO",
    SERIES: "SERIES",
    MOVIES: "MOVIES",
    RECENT: "AGREGADAS RECIENTEMENTE",
    POPULAR: "POPULARES",
    MY_MOVIES: "MIS PELICULAS",
    MY_LIST: "MI LISTA",
  },
  DROPDOWN: {
    POPULAR: "POPULARES",
    MY_MOVIES: "MIS PELICULAS",
  },
  ADD_MOVIE: {
    FILES_INPUT: "AGREGÁ UN ARCHIVO O ARRASTRALO Y SOLTALO AQUÍ",
    TITLE: "TÍTULO",
    UPLOAD_MOVIE: "SUBIR PELÍCULA",
    UPLOADED_HEADER: "¡FELICITACIONES!",
    UPLOADED_MESSAGE: " FUE CORRECTAMENTE SUBIDA.",
    READY: "¡LISTO!",
    LOADED: "100% CARGADO",
    CANCEL: "CANCELAR",
    ERROR_HEADER: "UPS :(",
    ERROR_MESSAGE: "Se produjo un error intentando subir la pelicula!",
    HOME: "IR A HOME",
    EXIT: "SALIR",
    SIZE_ERROR: "¡ERROR! EL PESO DEBE SER INFERIOR A 200KB.",
    TYPE_ERROR: "¡ERROR! EL FORMATO DEBE SER PNG, JPG O JPEG.",
    RETRY: "REINTENTAR",
  },
  ENV: {
    POPULAR: "popular",
    OUTSTANDING: "now_playing",
    MOVIES: "movies/",
    IMAGES: "images/",
    API_KEY: "6f26fd536dd6192ec8a57e94141f8b20",
    THE_MOVIE_DB: "https://api.themoviedb.org/3/movie/",
    MY_MOVIES_DB: "http://localhost:4000/",
  },
};

export default GLOBAL;
